name: RadPredict
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - prokka=1.14.6
  - diamond=2.0.15
  - pip=21.0
  - pandas=1.3.5
  - numpy=1.21.6
  - matplotlib=3.5.3
  - seaborn=0.12.0
  - scikit-learn=1.0.2
  - xgboost=1.6.2
  - ipython=8.4.0
  - flask=2.2.3
  - sqlalchemy=1.4.46
  - werkzeug=2.2.3
  - flask-sqlalchemy=3.0.3
  - python-dotenv=1.0.0
  - gunicorn=20.1.0
  - pip:
    - shap==0.41.0
